---
- name: create users
  include_tasks: users.yml

- name: create document root
  include_tasks: document-root.yml

- name: update httpd config
  include_tasks: update-httpd-conf.yml

- name: deploy code
  include_tasks: deploy-code.yml

- name: selinux task
  include_tasks: selinux.yml

- name: configure vhosts file
  include_tasks: vhosts.yml
